name: CI/CD Pipeline for eureka-server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install sshpass
        run: |
          sudo apt update
          sudo apt install sshpass -y

      - name: Verify sshpass installation
        run: |
          echo "Verify if sshpass installation"
          sshpass -V

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests
          echo "Build completed successfully"

      - name: Deploy to Hostinger
        env:
          HOSTINGER_IP: ${{ secrets.HOSTINGER_IP }}
          HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          echo "=============================================================================="
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no target/*.jar $HOSTINGER_USER@$HOSTINGER_IP:/root/applications/app.jar
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $HOSTINGER_USER@$HOSTINGER_IP << 'EOF'
            pkill -f 'java -jar' || true
            nohup java -jar /root/applications/app.jar > app.log 2>&1 &
          EOF
